### ISSUE TITLE
Small documentation change request

### ISSUE THREAD

**Issue by DutchessNicole** [NonaSuomy/WirePodVectorCommandHomeAssistant#1]
This is not a bug, just a small request.

Could  you break up the readme into two segments: one where you install the LLM, piper, whisper, and oww. And the second part where you install the plugin in wire-pod?

For my setup, I already have the voice pipelines set up, so none of that part of the documentation was relevant.

I really only needed to create and compile the plugin, and it works now.
It would make for an easier read for people who are only interested in the actual wirepod communication part.

Thanks!

**Comment by NonaSuomy** [comment]
Added table of contents
Also noticed in ReadMe's on github when you start scrolling it lists all the headers in the menu button at the top right
![image](https://github.com/NonaSuomy/WirePodVectorCommandHomeAssistant/assets/1906575/447d33c4-f6d4-47f1-a6a9-582c35f32701)
