### ISSUE TITLE
Small warning in documentation regarding agent_id field in plugin

### ISSUE THREAD

**Issue by DutchessNicole** [NonaSuomy/WirePodVectorCommandHomeAssistant#2]
I've just discovered that the agent_id field in the JSON post data causes the pipelines to break with a 400 message.

It seems that this is either not allowed anymore, or is not allowed when not using a custom LLM.

Perhaps it would be nice to add a warning to the documentation that the agent_id should only be used when going through the LLM steps.

**Comment by NonaSuomy** [comment]
https://github.com/NonaSuomy/WirePodVectorCommandHomeAssistant/blob/977aa80567ee03590c9e6f3dea9314830ae81018/README.md?plain=1#L621

Added this note, not sure about the second question, where are you seeing the html status code?

**Comment by DutchessNicole** [comment]
There is no second question in this issue, so if you added the comment then this issue is fine.
